name: scraper-v2

on:
  workflow_dispatch:

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'

      - name: Install python module
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: | 
          current_date=$(date +"%Y-%m-%d_%H-%M-%S")
          python -m scrapy crawl vlaanderenkiest_be -O results/results_${current_date}.csv:csv

      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/*.csv
          timestamp=$(TZ='America/New_York' date +'%a, %F at %H:%M %Z')
          git commit -m "Scraping updated: ${timestamp}" || exit 0
          git pull origin main --ff-only
          git push
